# Pipeline para TODO API Node.js con Redis (Node 8.17.0)
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # Older image that supports Node 8

variables:
  TODO_API_PORT: 8082
  JWT_SECRET: PRFT
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_CHANNEL: log_channel

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.17.0'
  displayName: 'Instalar Node.js 8.17.0'

- script: |
    sudo npm install -g npm@6.13.4
    cd todos-api
    npm install
    npm run build
    # Removed npm run build since it's not defined in your project
  displayName: 'Instalar dependencias'

- script: |
    cd todos-api
    sudo apt-get update
    sudo apt-get install -y redis-server
    redis-server --daemonize yes
  displayName: 'Configurar Redis'

- script: |
    cd todos-api
    JWT_SECRET=PRFT TODO_API_PORT=8082 npm start
  displayName: 'Iniciar aplicación'
  env:
    REDIS_HOST: $(REDIS_HOST)
    REDIS_PORT: $(REDIS_PORT)
    REDIS_CHANNEL: $(REDIS_CHANNEL)