# Pipeline para TODO API Node.js con Redis (Node 8.17.0)
trigger:
- master

pool:
  vmImage: 'ubuntu-18.04' # Oldest currently supported Ubuntu image

variables:
  TODO_API_PORT: 8082
  JWT_SECRET: PRFT
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_CHANNEL: log_channel

steps:
- script: |
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    sudo apt-get install -y nodejs=8.17.0-1nodesource1
    sudo npm install -g npm@6.13.4
    node -v
    npm -v
  displayName: 'Instalar Node.js 8.17.0 y npm 6.13.4'

- script: |
    cd todos-api
    npm install
    npm run build
  displayName: 'Instalar dependencias'

- script: |
    sudo apt-get update
    sudo apt-get install -y redis-server
    redis-server --daemonize yes
  displayName: 'Configurar Redis'

- script: |
    cd todos-api
    JWT_SECRET=PRFT TODO_API_PORT=8082 npm start
  displayName: 'Iniciar aplicación'
  env:
    REDIS_HOST: $(REDIS_HOST)
    REDIS_PORT: $(REDIS_PORT)
    REDIS_CHANNEL: $(REDIS_CHANNEL)