# Pipeline para TODO API Node.js con Redis
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - todos-api/**


pool:
  vmImage: ubuntu-latest

variables:
  TODO_API_PORT: 8082
  JWT_SECRET: PRFT
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_CHANNEL: log_channel

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Instalar Node.js'

- script: |
    cd todos-api
    npm install
    npm run build
  displayName: 'Instalar dependencias y construir'

  env:
    REDIS_HOST: $(REDIS_HOST)
    REDIS_PORT: $(REDIS_PORT)
    REDIS_CHANNEL: $(REDIS_CHANNEL)
