trigger:
  branches:
    include:
      - master
  paths:
    include:
      - auth-api/**

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN: '$(system.defaultWorkingDirectory)/bin' # Go binaries path
  GO_VERSION: '1.18.2' # Specific Go version

steps:
- task: GoTool@0
  inputs:
    version: '$(GO_VERSION)'
  displayName: 'Install Go $(GO_VERSION)'

- script: |
    mkdir -p '$(GOBIN)'
    echo '##vso[task.prependpath]$(GOBIN)'
  displayName: 'Set up the Go workspace'

- script: |
    ls -la $(system.defaultWorkingDirectory)
  displayName: 'List files in the working directory'

- script: |
    go version
    cd auth-api || exit 1
    if [ ! -f go.mod ]; then
        go mod init github.com/Salazq/microservice-app-example/tree/master/auth-api
    fi
    go mod tidy
    go mod download
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
    go build -v .
  workingDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'Get dependencies, then build'