trigger:
  branches:
    include:
      - master
  paths:
    include:
      - todos-api/**

pool:
  vmImage: ubuntu-latest

variables:
  - group: variable-group-taller

stages:
  - stage: Build_and_Test
    jobs:
      - job: InstallDeps
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '8.x'
            displayName: 'Instalar Node.js'

          - script: |
              cd todos-api
              npm install
              npm run build
            displayName: 'Instalar dependencias y construir'

  - stage: Deploy_to_VM
    dependsOn: Build_and_Test
    condition: succeeded()
    jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            name: GetPublicIP
            inputs:
              azureSubscription: $(AZURE_ACCOUNT)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                PUBLIC_IP=$(az vm show \
                  --name "$(VM_NAME)" \
                  --resource-group "$(RESOURCE_GROUP)" \
                  --show-details \
                  --query "publicIps" \
                  --output tsv)

                echo "##vso[task.setvariable variable=VM_PUBLIC_IP]$PUBLIC_IP"
                echo "IP pública obtenida: $PUBLIC_IP"
            displayName: 'Obtener IP pública de la VM'

          - script: |
              echo "Instalando sshpass..."
              sudo apt-get update && sudo apt-get install -y sshpass

              echo "Conectando por SSH con usuario y contraseña..."
              sshpass -p $(VM_PASSWORD) ssh -o StrictHostKeyChecking=no $(VM_USERNAME)@$(VM_PUBLIC_IP) << 'EOSSH'
                echo "Entrando al repositorio..."
                cd /home/azureuser/tu-repo
                sudo git pull origin master

                echo "Deteniendo el servicio todos-api si ya existe..."
                sudo docker-compose -f Docker-compose.yml stop todos-api || true
                sudo docker-compose -f Docker-compose.yml rm -f todos-api || true

                echo "Reconstruyendo y levantando solo el servicio todos-api..."
                sudo docker-compose -f Docker-compose.yml build todos-api
                sudo docker-compose -f Docker-compose.yml up -d todos-api

                echo "Todos-API desplegado correctamente en la VM usando docker-compose."
              EOSSH
            displayName: 'SSH para desplegar todos-api con docker-compose'