services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - app-network
    ports:
      - "9411:9411"

  auth-api:
    build:
      context: ./auth-api
    container_name: auth-api
    environment:
      - AUTH_API_PORT=8081
      - JWT_SECRET=PRFT
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - USERS_API_ADDRESS=http://users-api:8083
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - app-network

  users-api:
    build:
      context: ./users-api
    container_name: users-api
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=PRFT
    ports:
      - "8083:8083"
    depends_on:
      - auth-api
    networks:
      - app-network

  todos-api:
    build:
      context: ./todos-api
    container_name: todos-api
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    ports:
      - "8082:8082"
    depends_on:
      - redis
      - auth-api
    networks:
      - app-network

  log-message-processor:
    build:
      context: ./log-message-processor
    container_name: log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - redis
    networks:
      - app-network
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - AUTH_API_ADDRESS=http://nginx:80
      - TODOS_API_ADDRESS=http://nginx:80
      - ZIPKIN_URL=http://nginx:80/zipkin
    depends_on:
      - auth-api
      - users-api
      - todos-api
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - auth-api
      - todos-api
      - users-api
      - zipkin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  redis-data: